In [1]:
###库#####################################################################
import numpy as np
import pandas as pd
from datetime import datetime
import pickle
import matplotlib.pyplot as plot
import graphviz
from time import time
import random
import pydotplus 
import os
import re
import jieba
from numpy.random import randn
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.sparse import csr_matrix

import lightgbm as lgb
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.svm import LinearSVC, SVC
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from sklearn import tree

from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, confusion_matrix, roc_auc_score, roc_curve, auc

##################################
import warnings
warnings.filterwarnings('ignore')

from pylab import mpl
mpl.rcParams['font.sans-serif'] = ['FangSong'] # 指定默认字体
mpl.rcParams['axes.unicode_minus'] = False # 解决保存图像是负号'-'显示为方块的问题



from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"  #'all'|'last'|'last_expr'|'none'

class Tool():
    def __init__(self):
        self.input_path = '../input/'
        self.submi_path = '../submision/'

        self.__jieba_expend_dict()
    
    ###年龄分组
    def age_group(self, age):
        #用法：ori_data_28['age_group'] = ori_data_28.age.apply(age_group)
        if (age>=0) and (age<=10):
            return 0
        elif (age>10) and (age<=20):
            return 1
        elif (age>20) and (age<=30):
            return 2
        elif (age>30) and (age<=40):
            return 3
        elif (age>4) and (age<=50):
            return 4
        elif (age>50) and (age<=60):
            return 5
        elif (age>60) and (age<=70):
            return 6
        elif (age>70) and (age<=80):
            return 7
        elif (age>80) and (age<=90):
            return 8
        elif (age>90):
            return 9
    
    ###特征预处理
    def encode_count(self, df, encoder_list):
        lbl = LabelEncoder()
        for i in range(0, len(encoder_list)):
            df[[encoder_list[i]]] = lbl.fit_transform(df[[encoder_list[i]]])
        return df
    def encode_onehot(self, df, oneHot_list):
        for i in range(0, len(oneHot_list)):
            feature_df = pd.get_dummies(df[oneHot_list[i]], prefix=oneHot_list[i])
            df = pd.concat([df.drop([oneHot_list[i]], axis=1), feature_df], axis=1)
        return df
    def normalize(self, df, normalize_list):
        scaler = StandardScaler()
        for i in range(0, len(normalize_list)):
            df[[normalize_list[i]]] = scaler.fit_transform(df[[normalize_list[i]]])
        return df

    ###制作统计特征
    def feat_nunique(self, df_tar, df_fea, grou, stati, name):
        add_tem = df_fea.groupby(grou)[stati].nunique().reset_index()
        add_tem.columns = grou + name
        df_tar = pd.merge(df_tar, add_tem, on=grou, how='left')
        df_tar = df_tar.fillna(0)
        return df_tar
    def feat_mode(self, df_tar, df_fea, grou, stati, name):
        add_tem = df_fea.groupby(grou)[stati].mode().reset_index()
        add_tem.columns = grou + name
        df_tar = pd.merge(df_tar, add_tem, on=grou, how='left')
        df_tar = df_tar.fillna(0)
        return df_tar
    def feat_count(self, df_tar, df_fea, grou, stati, name):
        add_tem = df_fea.groupby(grou)[stati].count().reset_index()
        add_tem.columns = grou + name
        df_tar = pd.merge(df_tar, add_tem, on=grou, how='left')
        df_tar = df_tar.fillna(0)
        return df_tar
    def feat_sum(self, df_tar, df_fea, grou, stati, name):
        add_tem = df_fea.groupby(grou)[stati].sum().reset_index()
        add_tem.columns = grou + name
        df_tar = pd.merge(df_tar, add_tem, on=grou, how='left')
        df_tar = df_tar.fillna(0)
        return df_tar
    def feat_mean(self, df_tar, df_fea, grou, stati, name):
        add_tem = df_fea.groupby(grou)[stati].mean().reset_index()
        add_tem.columns = grou + name
        df_tar = pd.merge(df_tar, add_tem, on=grou, how='left')
        df_tar = df_tar.fillna(0)
        return df_tar
    def feat_max(self, df_tar, df_fea, grou, stati, name):
        add_tem = df_fea.groupby(grou)[stati].max().reset_index()
        add_tem.columns = grou + name
        df_tar = pd.merge(df_tar, add_tem, on=grou, how='left')
        df_tar = df_tar.fillna(0)
        return df_tar
    def feat_min(self, df_tar, df_fea, grou, stati, name):
        add_tem = df_fea.groupby(grou)[stati].min().reset_index()
        add_tem.columns = grou + name
        df_tar = pd.merge(df_tar, add_tem, on=grou, how='left')
        df_tar = df_tar.fillna(0)
        return df_tar
    
    ###特征选择
    def Tree_feature_select(self, X_train, y_train, X_test, y_test, sel_num): 
         ##最简单最常用
        clf = lgb.LGBMClassifier(n_estimators=200,
                                 learning_rate=0.6,
                                 max_depth=10,
                                 num_leaves=30,
                                 objective='binary',  #不需要指定类别，自动根据便签分类
                                 subsample=0.9,
                                 sub_feature=0.9,
                                 )
        clf = clf.fit(X_train, y_train, 
                      eval_set=[(X_test, y_test)], eval_metric='binary_logloss',
                      early_stopping_rounds=100, verbose = 500, 
                     )

        if type(X_train) is pd.core.frame.DataFrame:
            print('type(X_train) is DataFrame')
            feature_importances = sorted(zip(X_train.columns, clf.feature_importances_), key=lambda x: x[1], reverse=True)
            select_list = [feat[0] for feat in feature_importances[0: sel_num]]
            X_train_sel = X_train[select_list]
            X_test_sel = X_test[select_list]
        else:
            if type(X_train) is np.ndarray:
                print('type(X_train) is ndarray')
                feature_importances = sorted(zip(range(0, len(X_train[0])), clf.feature_importances_), key=lambda x: x[1], reverse=True)
                
            elif type(X_train) is csr_matrix:
                print('type(X_train) is csr_matrix')
                feature_importances = sorted(zip(range(0, X_train.get_shape()[1]), clf.feature_importances_), key=lambda x: x[1], reverse=True)

            select_list = [feat[0] for feat in feature_importances[0: sel_num]]
            X_train_sel = X_train[:, select_list]
            X_test_sel = X_test[:, select_list]

        return feature_importances, X_train_sel, X_test_sel
    def RFECV_feature_select(self, X_train, y_train, X_test):  
        ##天池的大佬经常使用！！！
        ###clf可以随便换！！！
        clf = LogisticRegression(penalty='l2',
                                 solver='liblinear', 
                                 )
        selector = RFECV(clf, step=1, cv=2)
        selector = selector.fit(X_train, y_train)

        X_train_select = selector.transform(X_train)
        X_test_select = selector.transform(X_test)

        return selector, X_train_select, X_test_select
    
    ###降维
    def PCA_decomposition(self, X_train, X_test, num):
        ##注pca不支持稀疏输入
        pca = PCA(num)
        pca.fit(X_train)
        low_X_train = pca.transform(X_train) 
        low_X_test = pca.transform(X_test) 

        return pca, low_X_train, low_X_test
    
    ###cnn特征提取
    def get_activation(self, nn_model, layer, X_origin):
        get_activations = bk.function([nn_model.layers[0].input, bk.learning_phase()], [nn_model.layers[layer].output])
        activations=get_activations([X_origin, 0])
        return activations
    
    ###评价指标
    def evaluate_matrix(self, y_test_class, y_pred_prob):
        y_pred_prob = [array[1] for array in y_pred_prob]  #因为sklearn输出每个类别的概率，手动选择1类
        y_pred_class = [1 if y>=0.50 else 0 for y in y_pred_prob]
        
        
        matrix = confusion_matrix(y_test_class, y_pred_class)
        print(matrix)
        
        if len(set(y_test_class)) == 2:  #二分类
            print('二分类')
            print('f1 score  ：', f1_score(y_test_class, y_pred_class))  
            print('precision：', precision_score(y_test_class, y_pred_class))
            print('recall：', recall_score(y_test_class, y_pred_class))
            print('accuracy：', accuracy_score(y_test_class, y_pred_class))
            print('AUC：', roc_auc_score(y_test_class, y_pred_prob))
        elif len(set(y_test_class)) > 2:  #多分类
            print('多分类')
            print('f1 score  ：', f1_score(y_test_class, y_pred_class, average='macro'))  
            print('precision：', precision_score(y_test_class, y_pred_class, average='macro'))
            print('recall：', recall_score(y_test_class, y_pred_class, average='macro'))
            print('accuracy：', accuracy_score(y_test_class, y_pred_class))
            pass


    ###jieba分词，调整
    def __jieba_expend_dict(self):
#         ###增加词典
#         jieba.add_word('背骶尾部')

#         ###调整词典
#         jieba.suggest_freq('撞到', True)

#         jieba.suggest_freq(('致', '右'), tune=False)
        pass
tool = Tool()

###其他工具函数
# pickle.dump(ori_data_28, open(tool.input_path + 'ori_data_28.pkl', 'wb'))
# ori_data_28 = pickle.load(open(tool.input_path + 'ori_data_28.pkl', 'rb'))

E:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

#### EDA

In [ ]:
'''
1、线上没有点击行为
2、没有人是“领取了优惠券”，但“购买时没有使用”？
3、如果没领取优惠券，但存在消费，那就是普通消费日期


4、领取券后，一般什么时候购买？
5、线下应该会早一点购买，线下不行

6、优惠券竟然不是唯一的，太奇怪了
7、怎么会有数据泄露呢？太奇怪了！
8、线下怎么领取消费券呢？是在线上先领取了，然后在线下购买？
   还是直接跑到别人的店铺里拿优惠券？

9、云泛天音的方案中，我估计他是做了多分



'''

In [2]:
online_train = pd.read_csv(tool.input_path + 'ccf_online_stage1_train.csv')
offline_train = pd.read_csv(tool.input_path + 'ccf_offline_stage1_train.csv')
offline_test = pd.read_csv(tool.input_path + 'ccf_offline_stage1_test_revised.csv')

online_train = online_train.fillna(-1)  
offline_train = offline_train.fillna(-1)
offline_test = offline_test.fillna(-1)


print('online_train:', online_train.shape)
print('offline_train:', offline_train.shape)
print('offline_test:', offline_test.shape)

online_train.head(2)
offline_train.head(2)
offline_test.head(2)

print('\n')
print('online_train:')
online_train.info()

print('\n')
print('offline_train:')
offline_train.info()

print('\n')
print('offline_test:')
offline_test.info()

online_train: (11429826, 7)
offline_train: (1754884, 7)
offline_test: (113640, 6)

,User_id,Merchant_id,Action,Coupon_id,Discount_rate,Date_received,Date
0,13740231,18907,2,100017492,500:50,20160513.0,-1.0
1,13740231,34805,1,-1,-1,-1.0,20160321.0

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date
0,1439408,2632,-1.0,-1,0.0,-1.0,20160217.0
1,1439408,4663,11002.0,150:20,1.0,20160528.0,-1.0

   User_id  Merchant_id  Coupon_id Discount_rate  Distance  Date_received
0  4129537          450       9983          30:5       1.0       20160712
1  6949378         1300       3429          30:5      -1.0       20160706

online_train:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11429826 entries, 0 to 11429825
Data columns (total 7 columns):
User_id          int64
Merchant_id      int64
Action           int64
Coupon_id        object
Discount_rate    object
Date_received    float64
Date             float64
dtypes: float64(2), int64(3), object(2)
memory usage: 610.4+ MB


offline_train:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1754884 entries, 0 to 1754883
Data columns (total 7 columns):
User_id          int64
Merchant_id      int64
Coupon_id        float64
Discount_rate    object
Distance         float64
Date_received    float64
Date             float64
dtypes: float64(4), int64(2), object(1)
memory usage: 93.7+ MB


offline_test:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113640 entries, 0 to 113639
Data columns (total 6 columns):
User_id          113640 non-null int64
Merchant_id      113640 non-null int64
Coupon_id        113640 non-null int64
Discount_rate    113640 non-null object
Distance         113640 non-null float64
Date_received    113640 non-null int64
dtypes: float64(1), int64(4), object(1)
memory usage: 5.2+ MB

In [3]:
offline_train.Discount_rate.unique()
offline_train.Distance.unique()

print('\n')
print('毫无疑问，基本上都是“满多少，减多少”的优惠券')

array([-1, '150:20', '20:1', '200:20', '30:5', '50:10', '10:5', '100:10',
       '200:30', '20:5', '30:10', '50:5', '150:10', '100:30', '200:50',
       '100:50', '300:30', '50:20', '0.9', '10:1', '30:1', '0.95',
       '100:5', '5:1', '100:20', '0.8', '50:1', '200:10', '300:20',
       '100:1', '150:30', '300:50', '20:10', '0.85', '0.6', '150:50',
       '0.75', '0.5', '200:5', '0.7', '30:20', '300:10', '0.2', '50:30',
       '200:100', '150:5'], dtype=object)

array([ 0.,  1., -1.,  2., 10.,  4.,  7.,  9.,  3.,  5.,  6.,  8.])

毫无疑问，基本上都是“满多少，减多少”的优惠券

In [6]:
coupon_byDate = offline_train[offline_train['Date_received'] != -1][['User_id', 'Date_received', 'Date']].groupby(['User_id', 'Date_received']).count()
coupon_byDate

                       Date
User_id Date_received
4       20160214.0        1
        20160607.0        1
35      20160129.0        2
        20160130.0        2
36      20160125.0        2
64      20160129.0        1
110     20160131.0        3
144     20160227.0        1
147     20160129.0        1
165     20160125.0        1
        20160322.0        1
        20160525.0        1
166     20160525.0        1
173     20160414.0        1
184     20160129.0        2
215     20160524.0        1
228     20160130.0        1
236     20160125.0        2
        20160211.0        1
        20160528.0        1
238     20160203.0        1
        20160608.0        1
239     20160614.0        2
285     20160501.0        1
311     20160329.0        1
        20160331.0        1
315     20160518.0        1
        20160519.0        1
316     20160430.0        1
318     20160214.0        1
...                     ...
7360725 20160129.0        3
7360728 20160521.0        1
7360758 20160123.0        1
7360760 20160126.0        3
7360785 20160131.0        1
7360797 20160326.0        2
        20160515.0        1
7360823 20160326.0        1
7360825 20160124.0        2
7360840 20160131.0        1
7360845 20160128.0        1
        20160410.0        1
        20160413.0        1
7360863 20160119.0        1
        20160128.0        1
        20160422.0        1
7360895 20160122.0        1
7360928 20160126.0        1
        20160423.0        1
        20160522.0        1
7360931 20160521.0        1
7360941 20160325.0        2
7360952 20160524.0        1
7360961 20160609.0        1
7360966 20160129.0        1
7360967 20160110.0        1
        20160120.0        1
        20160322.0        2
7361024 20160211.0        1
7361032 20160129.0        2

[829909 rows x 1 columns]

In [44]:
coupon_byDate = offline_train[offline_train['Date_received'] != -1][['User_id', 'Date_received', 'Date']].groupby(['User_id', 'Date_received'], as_index=False).count()
coupon_byDate.columns = ['User_id', 'Date_received','count']

buy_byDate = offline_train[(offline_train['Date'] != -1) & (offline_train['Date_received'] != -1)][['User_id', 'Date_received', 'Date']].groupby(['User_id', 'Date'], as_index=False).count()
buy_byDate.columns = ['User_id', 'Date','count']

print('在这些领了券的人当中，每一天倒是会领很多次，但是基本上一天当中只会消费一次')

在这些领了券的人当中，每一天倒是会领很多次，但是基本上一天当中只会消费一次

In [3]:
# 测试集中出现，但训练集没出现

print('用户：', len(set(offline_test.User_id) - set(offline_train.User_id)))
print('商店：', len(set(offline_test.Merchant_id) - set(offline_train.Merchant_id)))
print('优惠券：', len(set(offline_test.Coupon_id) - set(offline_train.Coupon_id)))

print('\n')
print('测试集上的数据，基本train上都有覆盖')

用户： 2
商店： 1
优惠券： 932


测试集上的数据，基本train上都有覆盖

In [4]:
###正样本
posi_sample_offLine = offline_train[(offline_train.Coupon_id != -1) & (offline_train.Date != -1)]
posi_sample_offLine.shape

###负样本
navi_sample_offLine = offline_train[(offline_train.Coupon_id != -1) & (offline_train.Date == -1)]
navi_sample_offLine.shape

print('怎么这么多人傻逼，有优惠券不用，我估计是“满多少减多少”，很少人真的买满的')

(75382, 7)

(977900, 7)

怎么这么多人傻逼，有优惠券不用，我估计是“满多少减多少”，很少人真的买满的

In [5]:
tem = sorted(online_train.Date_received.unique())
print('线上训练集，领取优惠券的最早时期：', tem[1])
print('线下训练集，领取优惠券的最早时期：', tem[1])
print('线上训练集，领取优惠券的最后时期：', tem[-1])
print('线下训练集，领取优惠券的最后时期：', tem[-1])
print('\n')

tem = sorted(online_train.Date.unique())
print('线上训练集，消费的最早时期：', tem[1])
print('线下训练集，消费的最早时期：', tem[1])
print('线上训练集，消费的最后时期：', tem[-1])
print('线下训练集，消费的最后时期：', tem[-1])

print('\n')
print('为什么到15号就停止“领券”了呢？奇怪啊')

线上训练集，领取优惠券的最早时期： 20160101.0
线下训练集，领取优惠券的最早时期： 20160101.0
线上训练集，领取优惠券的最后时期： 20160615.0
线下训练集，领取优惠券的最后时期： 20160615.0


线上训练集，消费的最早时期： 20160101.0
线下训练集，消费的最早时期： 20160101.0
线上训练集，消费的最后时期： 20160630.0
线下训练集，消费的最后时期： 20160630.0


为什么到15号就停止“领券”了呢？奇怪啊

In [6]:
print('online_train:')
print('有优惠券， 购买商品：', online_train[(online_train['Coupon_id'] != -1) & (online_train['Date'] != -1)].shape[0])
print('有优惠券， 没有购买商品：', online_train[(online_train['Coupon_id'] != -1) & (online_train['Date'] == -1)].shape[0])
print('无优惠券， 购买商品：', online_train[(online_train['Coupon_id'] == -1) & (online_train['Date'] != -1)].shape[0])
print('无优惠券， 没有购买商品：', online_train[(online_train['Coupon_id'] == -1) & (online_train['Date'] == -1)].shape[0])
print('\n')

print('offline_train:')
print('有优惠券， 购买商品：', offline_train[(offline_train['Coupon_id'] != -1) & (offline_train['Date'] != -1)].shape[0])
print('有优惠券， 没有购买商品：', offline_train[(offline_train['Coupon_id'] != -1) & (offline_train['Date'] == -1)].shape[0])
print('无优惠券， 购买商品：', offline_train[(offline_train['Coupon_id'] == -1) & (offline_train['Date'] != -1)].shape[0])
print('无优惠券， 没有购买商品：', offline_train[(offline_train['Coupon_id'] == -1) & (offline_train['Date'] == -1)].shape[0])
print('\n')

online_train:
有优惠券， 购买商品： 216459
有优惠券， 没有购买商品： 655898
无优惠券， 购买商品： 10557469
无优惠券， 没有购买商品： 0


offline_train:
有优惠券， 购买商品： 75382
有优惠券， 没有购买商品： 977900
无优惠券， 购买商品： 701602
无优惠券， 没有购买商品： 0

In [7]:
print('online_train的人数：', len(set(online_train.User_id)))
print('online_train的人数：', len(set(offline_train.User_id)))
print('offline_train和online_train的人数交集：', len(set(online_train.User_id) & set(offline_train.User_id)))

print('offline_test的人数：', len(set(offline_test.User_id)))
print('offline_train和offline_test的人数交集：', len(set(offline_train.User_id) & set(offline_test.User_id)))
print('\n')

print('online_train的优惠券数：', online_train.Coupon_id.nunique())
print('offline_train的优惠券数：', offline_train.Coupon_id.nunique())
print('offline_test的优惠券数：', offline_test.Coupon_id.nunique())

online_train的人数： 762858
online_train的人数： 539438
offline_train和online_train的人数交集： 267448
offline_test的人数： 76309
offline_train和offline_test的人数交集： 76307


online_train的优惠券数： 27748
offline_train的优惠券数： 9739
offline_test的优惠券数： 2050

#### 数据预处理

In [14]:
online_train = pd.read_csv(tool.input_path + 'ccf_online_stage1_train.csv')
offline_train = pd.read_csv(tool.input_path + 'ccf_offline_stage1_train.csv')
offline_test = pd.read_csv(tool.input_path + 'ccf_offline_stage1_test_revised.csv')

###空值填-1
online_train = online_train.fillna(-1)
offline_train = offline_train.fillna(-1)
offline_test = offline_test.fillna(-1)


###转化为时间格式
online_train['Date_received'] = online_train.Date_received.apply(lambda x: \
                                datetime(int(str(x)[0: 4]), int(str(x)[4: 6]), int(str(x)[6: 8])) if x != -1 else -1)   

offline_train['Date_received'] = offline_train.Date_received.apply(lambda x: \
                                datetime(int(str(x)[0: 4]), int(str(x)[4: 6]), int(str(x)[6: 8])) if x != -1 else -1)   

offline_test['Date_received'] = offline_test.Date_received.apply(lambda x: \
                                datetime(int(str(x)[0: 4]), int(str(x)[4: 6]), int(str(x)[6: 8])) if x != -1 else -1)   

online_train['Date'] = online_train.Date.apply(lambda x: \
                                datetime(int(str(x)[0: 4]), int(str(x)[4: 6]), int(str(x)[6: 8])) if x != -1 else -1)   

offline_train['Date'] = offline_train.Date.apply(lambda x: \
                                datetime(int(str(x)[0: 4]), int(str(x)[4: 6]), int(str(x)[6: 8])) if x != -1 else -1)   


online_train.head()
offline_train.head()
offline_test.head()


###打标签#############################
df_train = offline_train[offline_train['Coupon_id'] != -1].reset_index(drop=True)  #只选取了领取优惠券的人

df_train['diff'] = df_train.apply(lambda x: (x.Date - x.Date_received).days if x.Date != -1 else -1, axis=1)
df_train['is_buy'] = df_train['diff'].apply(lambda x: 0 if(x > 15 or x == -1) else 1)


df_test = offline_test

pickle.dump(df_train, open(tool.input_path + 'df_train.pkl', 'wb'))
pickle.dump(df_test, open(tool.input_path + 'df_test.pkl', 'wb'))

,User_id,Merchant_id,Action,Coupon_id,Discount_rate,Date_received,Date
0,13740231,18907,2,100017492,500:50,2016-05-13 00:00:00,-1
1,13740231,34805,1,-1,-1,-1,2016-03-21 00:00:00
2,14336199,18907,0,-1,-1,-1,2016-06-18 00:00:00
3,14336199,18907,0,-1,-1,-1,2016-06-18 00:00:00
4,14336199,18907,0,-1,-1,-1,2016-06-18 00:00:00

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date
0,1439408,2632,-1.0,-1,0.0,-1,2016-02-17 00:00:00
1,1439408,4663,11002.0,150:20,1.0,2016-05-28 00:00:00,-1
2,1439408,2632,8591.0,20:1,0.0,2016-02-17 00:00:00,-1
3,1439408,2632,1078.0,20:1,0.0,2016-03-19 00:00:00,-1
4,1439408,2632,8591.0,20:1,0.0,2016-06-13 00:00:00,-1

   User_id  Merchant_id  Coupon_id Discount_rate  Distance Date_received
0  4129537          450       9983          30:5       1.0    2016-07-12
1  6949378         1300       3429          30:5      -1.0    2016-07-06
2  2166529         7113       6928        200:20       5.0    2016-07-27
3  2166529         7113       1808        100:10       5.0    2016-07-27
4  6172162         7605       6500          30:1       2.0    2016-07-08

#### 特征工程

In [9]:
def discount_rate(str_rate):
    list_ = re.findall('\d*', str_rate)
    a = int(list_[0])
    b = int(list_[2])
    
    if a != 0: 
        float_rate = (a - b) / a
    else:
        float_rate = float(str_rate)
    
    return float_rate
def discount_rate_man(str_rate):
    if re.search(':', x):
        list_ = re.findall('\d*', str_rate)
        a = int(list_[0])
        b = int(list_[2])
        
        return a
    else:
        return 0
def discount_rate_jian(str_rate):
    if re.search(':', x):
        list_ = re.findall('\d*', str_rate)
        a = int(list_[0])
        b = int(list_[2])
        
        return b
    else:
        return 0

    
df_train = pickle.load(open(tool.input_path + 'df_train.pkl', 'rb'))
df_test = pickle.load(open(tool.input_path + 'df_test.pkl', 'rb'))

    
df_train['month'] = df_train.Date_received.dt.month
df_train['day'] = df_train.Date_received.dt.day
df_train['weekday'] = df_train.Date_received.dt.weekday
df_train['is_weekend'] = df_train.weekday.apply(lambda x: 0 if x<=4 else 1)
df_train['discount_rate'] = df_train.Discount_rate.apply(discount_rate)
df_train['discount_rate_type'] = df_train.Discount_rate.apply(lambda x: 1 if re.search(':', x) else 0)
df_train['discount_rate_man'] = df_train.Discount_rate.apply(discount_rate)
df_train['discount_rate_jian'] = df_train.Discount_rate.apply(discount_rate)

In [ ]:
df_test['month'] = df_test.Date_received.dt.month
df_test['day'] = df_test.Date_received.dt.day
df_test['weekday'] = df_test.Date_received.dt.weekday
df_test['is_weekend'] = df_test.weekday.apply(lambda x: 0 if x<=4 else 1)
df_test['discount_rate'] = df_test.Discount_rate.apply(discount_rate)
df_test['discount_rate_type'] = df_test.Discount_rate.apply(lambda x: 1 if re.search(':', x) else 0)
df_test['discount_rate_man'] = df_test.Discount_rate.apply(discount_rate)
df_test['discount_rate_jian'] = df_test.Discount_rate.apply(discount_rate)

#### 跑模型

In [22]:
###验证集的划分！
df_train_ = df_train[df_train.Date_received < datetime(2016, 5, 16)]
df_val = df_train[df_train.Date_received >= datetime(2016, 5, 16)]


###特征标签划分
base_feat = ['month', 'day', 'weekday', 'is_weekend', 'Distance', 'discount_rate', 'discount_rate_type',]

###线下验证，提交分数下降
# 'discount_rate_man', 'discount_rate_jian',这两个特征会扣分，估计确实不会随意堆特征啊

###提交，加了分数会下降的特征：
# 'weekday', 'is_weekend', 'discount_rate', 'discount_rate_type',



all_feat = base_feat

X_train_ = df_train_[all_feat]
y_train_ = df_train_['is_buy']

X_val = df_val[all_feat]
y_val = df_val['is_buy']


X_test = df_test[all_feat]

In [23]:
###模型训练预测
def clf_train(X_train, y_train, X_val, y_val):
    categorical_feature = ['性别', '入院科室']
    clf = lgb.LGBMClassifier(n_estimators=10000,
                                   learning_rate=0.06,
                                   max_depth=5,
                                   num_leaves=30,
                                   objective='binary',
                                   subsample=0.8,
                                   sub_feature=0.8,
#                                    class_weight='balanced',  #设置样本平衡；好像不要会更好
                                   )
    clf.fit(X_train, y_train, eval_set=[(X_val, y_val)], eval_metric='binary_logloss',
            early_stopping_rounds=100, verbose = 5000,
#             categorical_feature = categorical_feature    #onehot之后就不需要了
            )
    feat_impo = sorted(zip(X_train.columns, clf.feature_importances_), key=lambda x: x[1], reverse=True)
    
    return clf, feat_impo 
def clf_predict(clf, X_val):
    y_pred = clf.predict_proba(X_val, num_iteration=clf.best_iteration)
    
    return y_pred
def clf_evaluate(df_val, y_pred_):
    y_pred_ = y_pred_[:, 1]  #因为sklearn输出每个类别的概率，手动选择1类
    
    df_val_auc = df_val[['Coupon_id', 'is_buy']]
    df_val_auc['pred_prob'] = y_pred_

    # 计算平均AUC
    vg = df_val_auc.groupby(['Coupon_id'])
    aucs = []
    for i in vg:   #这个“i”是分好组子集
        df_tem = i[1]

        if len(df_tem['is_buy'].unique()) != 2:
            continue

        fpr, tpr, thresholds = roc_curve(df_tem['is_buy'], df_tem['pred_prob'], pos_label=1)
        aucs.append(auc(fpr, tpr))
    print('平均auc为：', np.average(aucs))


start_time = time()

clf, feat_impo = clf_train(X_train_, y_train_, X_val, y_val)
y_pred_ = clf_predict(clf, X_val)
clf_evaluate(df_val, y_pred_)

print('训练预测的时间为:', int(time() - start_time))

Train until valid scores didn't improve in 100 rounds.
Early stopping, best iteration is:
[75]	valid_0's binary_logloss: 0.295437
平均auc为： 0.537888813948266
训练预测的时间为: 11

In [25]:
y_pred = clf_predict(clf, X_test)
y_pred = [array[1] for array in y_pred]



submission = pd.read_csv(tool.input_path + 'ccf_offline_stage1_test_revised.csv')[['User_id', 'Coupon_id', 'Date_received']]
df_tem = pd.DataFrame(y_pred, columns=['Probability'])
submission = pd.concat([submission, df_tem], axis=1)

submission.to_csv(tool.submi_path + '8_6_v1.csv', index =False, header=None)

#### 可能用到的代码保存

In [ ]:
###空值填-1
df_train_ = df_train_.replace({-1: np.nan})
df_val = df_val.replace({-1: np.nan})
df_test = df_test.replace({-1: np.nan})

In [58]:
import numpy as np
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

y_true = np.array([1, 1, 0, 1])
y_pred = np.array([0.1, 0.4, 0.35, 0.8])


fpr, tpr, thresholds = roc_curve(y_true, y_pred, pos_label=1)
print('AUC：', auc(fpr, tpr))


print('AUC：', roc_auc_score(y_true, y_pred))

AUC： 0.6666666666666666
AUC： 0.6666666666666666

In [34]:
a = set([1,2,3]) 
b = set([1,4,5])

##交集，并集
a & b
b & a

a | b
b | a

##差集
a - b
b - a

{1}

{1}

{1, 2, 3, 4, 5}

{1, 2, 3, 4, 5}

{2, 3}

{4, 5}

In [96]:
a = datetime(2011, 1, 1) - datetime(2010, 1, 1)
a
a.days

b = datetime(2011, 1, 1)
b
b.day

datetime.timedelta(365)

365

datetime.datetime(2011, 1, 1, 0, 0)

1

In [ ]:
###正样本
posi_sample_offLine = offline_train[(offline_train.Coupon_id != -1) & (offline_train.Date != -1)]
posi_sample_offLine['is_buy'] = 1

###负样本
navi_sample_offLine = offline_train[(offline_train.Coupon_id != -1) & (offline_train.Date == -1)]
navi_sample_offLine['is_buy'] = 0

df_train = pd.concat([posi_sample_offLine, navi_sample_offLine], axis=0).reset_index(drop=True)

df_train['diff'] = df_train['Date'] - df_train['Date_received']
df_train['is_buy'] = df_train.apply(lambda x: 0 if(x.diff > 15 or x.Date == -1) else 1 )

df_train

In [36]:
list_ = [[1,3,2], [3,2,4], [2,1,5]]
df = pd.DataFrame(list_, columns=['a', 'b', 'c'])
df

df.sort_values(by='a')

   a  b  c
0  1  3  2
1  3  2  4
2  2  1  5

   a  b  c
0  1  3  2
2  2  1  5
1  3  2  4

In [ ]:
df_train.sort_values(by='Date_received')
user_action = user_action.groupby(['user_id']).apply(lambda x: x.sort_values('a_date')).reset_index(drop=True)